[tool.poetry]
name = "your-project"
version = "0.1.0"
description = "Your project description"

[tool.poetry.dependencies]
python = "^3.9"
supabase = "^2.2.1"
fastapi = "^0.104.0"
pydantic = "^2.4.2" 